#### CONFIG CREDENTIALS ####
spring :
  profiles :
    active : dev

microservices :
  items :
     -
        name : service-b
        host : localhost
        port : 8080
     -
        name : service-a
        host : localhost
        port : 8081

#### EUREKA CONFIG ####
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/