#### CONFIG CREDENTIALS ####
spring :
  profiles :
    active : dev,security,webMvc
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  ### RABBIT MQ CONFIG###
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

### MYALDOC AUTHENTICATION PROPERTIES ###
myaldoc :
  auth :
    userRetrieveUri : http://localhost:9000/user/retrieve

#### EUREKA CONFIG ####
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
