#### CONFIG CREDENTIALS ####
spring :
  profiles :
    active : dev,security


#### EUREKA CONFIG ####
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/