#### CONFIG CREDENTIALS ####
spring :
  profiles :
    active : dev,security,webMvc

  ### RABBIT MQ CONFIG###
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

### AUTHENTICATION PROPERTIES ###
myaldoc :
  auth :
    authenticationUri : http://localhost:9000/user/authenticate

#### EUREKA CONFIG ####
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/